#!/usr/bin/env ruby
print "Would you like to set this machine up as an RPM repository?\n"
answer = $stdin.gets.chomp
if answer == 'y'
  print "OK - setting up RPM repo.\n"
else
  print "OK - installing locally\n"
end
